site_name: Ymir-Executor Documence
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: numpy
  - include_dir_to_nav
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: "#"
#  - sane_lists
nav:
  - index.md
  - read.md
  - write.md
  - dataset_convert.md
  - history.md
